name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    permissions:
      contents: write    
    uses: krn-sebastiaan/mmojo-workflows/.github/workflows/release.yml@main
    secrets: inherit
